FEATURE ADD : Derived keys, Serialization of Secret Keys
tlepoint/fhe.rs pull request #179
Opened 2023-06-07 21:47 UTC by shankars99

Hey I added a function that allows the user to derive a key from a seed in addition to serializing and storing the secret key as a file.

2023-06-08 15:20 UTC, shankars99 commented
I'm trying to fix a bug in it. It passed all the test cases but when I added the forked repository as a cargo package into another project I ran into some issues. So I'm just trying to iron those out, once that's done I'll create a new PR

2023-06-08 19:50 UTC, tlepoint requested changes
Thanks for the PR; I sent a few comments to make the library more consistent with what we currently have.

2023-06-08 19:50 UTC, tlepoint commented on .gitignore
> +*.key
Let's use temporary files in the tests and remove this line instead

2023-06-08 19:50 UTC, tlepoint commented on crates/fhe-util/src/lib.rs
> +        let rng = rng.unwrap();
This may fail if the library wasn't called correctly (i.e., `None` is passed twice). 

I would prefer that we keep a `&mut R` as input, and instead instantiate the `&mut R` from the `der_key` outside of this function, the same way it is done https://github.com/tlepoint/fhe.rs/blob/main/crates/fhe-math/src/rq/mod.rs#L250-L251 for example.

2023-06-08 19:50 UTC, tlepoint commented on crates/fhe/src/bfv/keys/secret_key.rs
> +        let key_file = file_name.clone() + ".key";
Why do you add `.key` to the filename? I would prefer if the API was taking a `File` as input, so we don't have to worry in this library on failing to create it (e.g., wrong permissions). Instead, we will receive the file, and call `.write_all()` on it.

2023-06-08 19:50 UTC, tlepoint commented on crates/fhe/src/bfv/keys/secret_key.rs
> +            sample_vec_cbd(par.degree(), par.variance, Some(rng), Some(der_key)).unwrap();
Doing the suggestion above would prevent this weird cases were both a RNG and der_key are specified, and the RNG is ignored.

2023-06-08 19:50 UTC, tlepoint commented on crates/fhe/src/bfv/keys/secret_key.rs
> +        json.as_bytes().to_vec()
Could you make sure to zeroize the memory before exiting? See e.g., https://github.com/tlepoint/fhe.rs/blob/main/crates/fhe/src/bfv/keys/secret_key.rs#LL69C20-L69C20

2023-06-08 19:50 UTC, tlepoint commented on crates/fhe-util/src/lib.rs
> +        let rng = rng.unwrap();
Note that I am not opposed to tiny-keccak if it has the right traits to be passed as parameter; however using ChaCha may be easier there.

2023-06-08 19:53 UTC, tlepoint commented on Cargo.toml
> +version = "0.1.0-beta.5"
If you change the version (which will require a release after merge), could you please also update the README file? Alternatively, you can directly depend on a specific of the GitHub repo for your own project, until a new version is released.

2023-06-08 22:29 UTC, shankars99 commented
Thanks a lot for the comments I'll try to get through it by tomorrow and reopen this PR with them

2023-09-30 21:52 UTC, closed without merging

2023-09-30 21:52 UTC, tlepoint commented
I'll close this; feel free to reopen if you eventually want to merge something like that.