Multipary BFV
tlepoint/fhe.rs pull request #218
Opened 2023-10-27 16:28 UTC by samtay

As discussed in #216, this is a prototype implementation of [Multipary BFV](https://eprint.iacr.org/2020/304.pdf). Some things to be aware of:

1. Serialization/deserialization has not been implemented. I typically lean on `serde` for such things, but that would be a departure from the current library, and I'm not very familiar with the `prost` crate you're using.
2. Like your single-key relinearization key (RLK), the multiparty RLK is only available when ciphertext moduli length is greater than 1. (Note: It looks like since I started this implementation, you're now supporting moduli length 1 key switching keys, and I imagine you will extend this to RLK? If you do, I don't _think_ it would be difficult to adapt the multiparty RLK to support moduli length of 1 as well.)
3. Multipary RLKs are only implemented at level 0.
4. The only difference from the paper is that "noise flooding" (relevant for key switching and decryption) is not implemented, but rather we draw flooding noise from the usual error distribution, i.e. $\chi_{smg} = \chi$. I've called out the two locations where this happens with `TODO` comments. The paper calls for this distribution to have a very large variance, and should actually not be static for a given parameter set, but rather drawn with variance proportional to the variance of a given ciphertext noise: $\sigma_{smg}^2 := 2^{\lambda} \sigma_{ct}^2$ (see p6 in paper linked above). A slightly better solution than the current implementation would be to have a separate smudging variance $\sigma_{smg}$ defined in the BFV params, so a larger variance can be specified. To accomplish full noise flooding in proportion to a given ciphertext, some information about the ciphertext noise variance would have to be passed as an argument to the key switching / decryption protocols, complicating the API.

I think that covers everything. In terms of the functionality provided here, I think both looking at the `cargo doc`s and seeing the example usage in the voting example or even the tests should suffice. Really, the multiparty setting only differs in that the secret key is distributed, so only operations that depend on the secret key (public key gen, relin key gen, decryption) need multiparty protocols. Everything else gets to lean on types and functionality already present in the `fhe` crate.

It is very much a prototype, so if you are not comfortable merging as is, that's totally understandable!

2023-10-27 17:14 UTC, tlepoint requested changes
Thank you for creating the PR!

Will continue the review later, just wanted to post some comments now.

Could you please run
```
cargo +nightly fmt --all -- --check
```
?

The unit test seems to fail also; it seems due to the key switching key? To answer your question, indeed I recently modified the key switching key for the last level (but it was a "hack", it's not very well designed). It would be great to improve this.

2023-10-27 17:14 UTC, tlepoint commented on crates/fhe/examples/util.rs
> +            use util::DisplayDuration;
Ah interesting: did you think that calling the other macro was affecting the performance?

2023-10-27 17:14 UTC, tlepoint commented on crates/fhe/src/mbfv/mod.rs
> +//! The Multiparty BFV scheme, as described by Christian Mouchet et. al.
Could you add the paper link please?

2023-10-27 17:14 UTC, tlepoint commented on crates/fhe/src/mbfv/public_key_switch.rs
> +        h1 += e1.as_ref();
Should `h0` and `h1` allow for variable time computation?

```rust
unsafe {
h0.allow_variable_time_computations();
h1.allow_variable_time_computations();
}
```

2023-10-27 17:14 UTC, tlepoint commented on crates/fhe/src/mbfv/public_key_gen.rs
> +
Maybe add
```rust
unsafe { p0_share.allow_variable_time_computations() }
```
?

2023-10-27 17:14 UTC, tlepoint commented on crates/fhe/src/mbfv/aggregate.rs
> +/// This trait exists for convenience; the `aggregate` method is analagous to
analogous

2023-10-27 17:37 UTC, samtay commented on crates/fhe/examples/util.rs
> +            use util::DisplayDuration;
No actually, this is because the compiler isn't smart enough to realize the loop is empty when `n == 1` and shouldn't move a variable. Without this change to the macro, the code

```rust
let tally_pt = timeit!("Decryption share aggregation", {
    let pt: Plaintext = decryption_shares.into_iter().aggregate()?;
    pt
});
```

expands to

```rust
let tally_pt = {
    use util::DisplayDuration;
    let start = std::time::Instant::now();
    #[allow(clippy::reversed_empty_ranges)]
    for _ in 1..1 {
      let _ = {
        let pt:Plaintext = decryption_shares.into_iter().aggregate()?;
        pt
      };
    }
    let r = {
      let pt:Plaintext = decryption_shares.into_iter().aggregate()?;
      pt
    };
    {
      $crate::io::_print(builtin #format_args("⏱  {}: {}","Decryption share aggregation",DisplayDuration(start.elapsed()/1)));
    };
    r
  };
```

and the compiler will complain about using `decryption_shares` after moving into the loop.

This change to the macro seemed like the easiest way to get around this.

2023-11-04 20:28 UTC, tlepoint approved these changes
Thanks for the change!

2023-11-08 02:36 UTC, merged