faster constant time reduction from [0, 2p)
tlepoint/fhe.rs pull request #238
Opened 2024-01-15 14:44 UTC by fionser

Faster constant-time selection. Show 10%+ improvement in ntt/intt in Apple M2 machine.

2024-01-15 15:09 UTC, tlepoint requested changes

2024-01-15 15:09 UTC, tlepoint commented on crates/fhe-math/src/zq/mod.rs
> +pub const fn const_time_cond_select(on_true: u64, on_false: u64, cond: bool) -> u64 {
Could we not make this public since it's only used in this file?

2024-01-15 15:09 UTC, tlepoint commented on crates/fhe-math/src/zq/mod.rs
> +}
From a quick glance using the compiler explorer, I see a jump operation. https://godbolt.org/z/jdKqGMdsn
I have not checked what is happening exactly, but have you verified that the resulting code is indeed constant-time?

Alternatively, we could create a feature to always perform variable time operations if this helps you.

2024-01-16 01:38 UTC, fionser commented on crates/fhe-math/src/zq/mod.rs
> +}
I learn this trick basically from the Curve25519's code. The constant-time conditional swap is very common in ECC. 
For instance https://eprint.iacr.org/2020/956.pdf.

The `jne` jump seems an error handle which seems not calling at all.
```
example::const_time_cond_select:
        sub     rsp, 24
        mov     qword ptr [rsp], rsi
        mov     qword ptr [rsp + 8], rdi
        mov     al, dl
        and     al, 1
        movzx   eax, al
        mov     qword ptr [rsp + 16], rax
        movabs  rcx, -9223372036854775808
        cmp     rax, rcx
        sete    al
        test    al, 1
        jne     .LBB0_2
        mov     rcx, qword ptr [rsp]
        mov     rax, qword ptr [rsp + 8]
        mov     rsi, qword ptr [rsp + 16]
        xor     edx, edx
        sub     rdx, rsi
        xor     rax, rcx
        and     rax, rdx
        xor     rax, rcx
        add     rsp, 24
        ret
.LBB0_2:
        lea     rdi, [rip + str.0]
        lea     rdx, [rip + .L__unnamed_1]
        mov     rax, qword ptr [rip + core::panicking::panic@GOTPCREL]
        mov     esi, 31
        call    rax
        ud2
```

2024-01-16 01:48 UTC, fionser commented on crates/fhe-math/src/zq/mod.rs
> +}
The `rax` and `rcx` regisiter will not equal (since `rax` only contain one byte)
```
        mov     qword ptr [rsp + 16], rax
        movabs  rcx, -9223372036854775808
        cmp     rax, rcx
        sete    al
        test    al, 1
        jne     .LBB0_2
```

2024-01-16 23:06 UTC, tlepoint commented on crates/fhe-math/src/zq/mod.rs
> +}
Ok sounds good! Could you please remove the `pub` keyword from above, and we can merge?

2024-01-17 03:13 UTC, tlepoint approved these changes

2024-01-17 03:13 UTC, merged

2024-01-17 03:13 UTC, tlepoint commented
Thank you!